### PR TITLE
Bump Workbook Versions to 1.0.5

### PR DESCRIPTION
**Pull request by jperson1**
# Bump Workbook Versions to 1.0.5

Issue: https://github.com/GSA-TTS/FAC/issues/3490

## Changes:
1. Add FMCSA as valid cluster name:
    * https://github.com/GSA-TTS/FAC/issues/3490, with a subsequent fix in https://github.com/GSA-TTS/FAC/pull/3513
2. New validations on the reference number in the CAP text and findings text workbooks

### CODE REVIEW

**Comment by jadudm** [comment]
Does this update the relevant validation pathways to allow v1.0.5 workbooks? 

Ah. Sorry. Did the relevant changes already happen in the app, I guess is my question.

If so, I'll approve this through.

**Comment by jperson1** [comment]
@jadudm Yes! The apps-side changes are complete, this PR is to update the templates that users can access.

The last change to workbooks was from PR https://github.com/GSA-TTS/FAC/pull/3513, which went into production this morning (https://github.com/GSA-TTS/FAC/releases/tag/v1.2040320).

**Review by jadudm — COMMENTED** [review]
LGTM.

**Review by jadudm — APPROVED** [review]
LGTM.

**Pull request merged**
