### PR TITLE
Lh/april fac updates

### PR DESCRIPTION
**Pull request by lauraherring**
This PR covers the latest addition to [the FAC Updates page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/april-fac-updates/updates/), as well as moving the previous update to [the archive page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/april-fac-updates/updates/archive/).

Screenshot 2024-04-18 at 09-32-33 Updates from the FAC

Screenshot 2024-04-18 at 09-32-44 Archived updates from the FAC

### CODE REVIEW

**Comment by jadudm** [comment]
Awesomesauce.

Two comments for the update:

1. We can link to https://www.fac.gov/api/tribal/ for the tribal API section; we have info about it.
2. Should we remove the general notice about accepting Tribal audits? I think that's just a given at this point?

**Comment by lauraherring** [comment]
@jadudm Great suggestions. I've made both of those and pushed a new commit.

**Comment by James-Paul-Mason** [comment]
The main title above the "March Peak Season" subtitle appears as "February 26th, 2024." Unless I'm misinterpreting something, shouldn't this read "April 18th, 2024"? Everything else looks great.

**Comment by lauraherring** [comment]
@James-Paul-Mason Great catch, I've pushed a commit to update that to this week's date.

**Comment by lauraherring** [comment]
@jadudm @James-Paul-Mason I pushed commits to address all of your suggestions. If you could re-review and approve when you get a chance, that'd be great.

**Review by James-Paul-Mason — APPROVED** [review]
I still see the February date listed instead of April.

**Pull request merged**
